name: tensorflow-cpu
channels:
  - defaults
dependencies:
- python=3.7
- h5py
- imageio
- seaborn
- kiwisolver
- jupyter
- markdown
- matplotlib
- numpy
- pandas
- flask
- pillow
- scipy
- scikit-learn
- scikit-image
- tensorflow